using System;
using System.Threading.Tasks;

namespace Altinn.Platform.Authentication.Services.Interfaces;

/// <summary>
/// The Service that support the CRUD API for administration of SystemUser-Requests
/// </summary>
public interface IRequestSystemUser
{
    /// <summary>
    /// Create a new Request for a SystemUser
    /// </summary>
    /// <param name="requestId">UUID4 Id generated by the Vendor which will be used by us; also will be reused by the SystemUser when it is approved</param>
    /// <param name="systemUserOrgNo">The organisation number for the SystemUser's end-user ( the customer that delegates rights to the systemuser) </param>
    /// <param name="externalRef">Either just the Orgno for the customer, or a TenantId or other form of disambiguation Id the Vendor needs.</param>
    /// <param name="description">Description written by the Vendor to display on the Acccept page</param>    /// 
    /// <returns>Returns 201 Ok with a link to the Status API for the Request</returns>
    Task CreateRequest(Guid requestId, string systemUserOrgNo, string externalRef, string description);
}
