namespace Altinn.Platform.Authentication.Core.Models.SystemUsers;

/// <summary>
/// Response through the API after Vendor calls to Create a new Request for a SystemUser
/// </summary>
/// <param name="Id">UUID4 Id generated by the Vendor which will be used by us; also will be reused by the SystemUser when it is approved</param>
/// <param name="ExternalRef">Either just the Orgno for the customer, or a TenantId or other form of disambiguation Id the Vendor needs.</param>
/// <param name="SystemId">The Id for the Registered System that this Request will be based on.</param>
/// <param name="PartyOrgNo">The organisation number for the SystemUser's Party ( the customer that delegates rights to the systemuser) </param>
/// <param name="Rights">The set of Rights requested for this system user. Must be equal to or less than the set defined in the Registered System</param>
/// <param name="Status">Initially the request is "new", and unless there are problems, the customer "accepted" it. </param>
/// <param name="RedirectURL">Optional redirect URL to navigate to after the customer has accepted/denied the Request</param>
/// <param name="SystemUserId">Initially this is null, but after an "accepted" request will be the Guid for the SystemUser created</param>
/// <returns>Returns 201 Ok with a response model</returns>
public sealed record CreateRequestSystemUserResponse(
    Guid Id, 
    string ExternalRef, 
    string SystemId, 
    string PartyOrgNo, 
    List<Right> Rights, 
    string Status, 
    string? RedirectURL = default, 
    string? SystemUserId = default);
