namespace Altinn.Platform.Authentication.Core.Models.SystemUsers;

/// <summary>
/// Response DTO through the API after Vendor calls to Create a new Request for a SystemUser
/// </summary>
public class CreateRequestSystemUserResponse()    
{
    /// <summary>
    /// UUID4 Id generated by the Vendor which will be used by us; also will be reused by the SystemUser when it is approved
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Either just the Orgno for the customer, or a TenantId or other form of disambiguation Id the Vendor needs.
    /// </summary>
    public string ExternalRef { get; set; }

    /// <summary>
    /// The Id for the Registered System that this Request will be based on.
    /// </summary>
    public string SystemId { get; set; }

    /// <summary>
    /// The organisation number for the SystemUser's Party ( the customer that delegates rights to the systemuser) 
    /// </summary>
    public string PartyOrgNo { get; set; }

    /// <summary>
    /// The set of Rights requested for this system user. Must be equal to or less than the set defined in the Registered System
    /// </summary>
    public List<Right> Rights { get; set; }

    /// <summary>
    /// Initially the request is "new", 
    /// other values are "accepted", "rejected", "denied"
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// Optional redirect URL to navigate to after the customer has accepted/denied the Request
    /// </summary>
    public string? RedirectURL { get; set; }

    /// <summary>
    /// Initially this is null, but after an "accepted" request will be the Guid for the SystemUser created
    /// </summary>
    public string? SystemUserId { get; set; } 
}
