namespace Altinn.Platform.Authentication.Core.Models.SystemUsers;

/// <summary>
/// Create a new Request for a SystemUser
/// </summary>
/// <param name="Id">UUID4 Id generated by the Vendor which will be used by us; also will be reused by the SystemUser when it is approved</param>
/// <param name="ExternalRef">Either just the Orgno for the customer, or a TenantId or other form of disambiguation Id the Vendor needs.</param>
/// <param name="SystemId">The Id for the Registered System that this Request will be based on.</param>
/// <param name="PartyOrgNo">The organisation number for the SystemUser's Party ( the customer that delegates rights to the systemuser) </param>
/// <returns>Returns 201 Ok with a response model</returns>
public sealed record CreateRequestSystemUser(Guid Id, string ExternalRef, string SystemId, string PartyOrgNo, List<Right> Rights, string? RedirectURL = default);

