name: API Bug Report
description: Report an issue related to the API.
title: "[Bug]: "
labels: ["bug"]
projects: ["Altinn/75"]
assignees:
  - Nyeng
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an API bug! Please provide as much detail as possible to help us diagnose and resolve the issue.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: endpoint
    attributes:
      label: API Endpoint
      description: Specify the affected API endpoint.
      placeholder: ex. POST /api/v1/users
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step list to reproduce the issue, including request method, headers, and body.
      placeholder: |
        1. Endpoint: POST /api/v1/users
        2. Request Method: POST
        3. Request Headers:
           {
             "Content-Type": "application/json",
             "Authorization": "Bearer <token>"
           }
        4. Request Body:
           {
             "username": "testuser",
             "email": "test@example.com",
             "password": "securePassword123"
           }
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: ex. The API should return a 201 Created status with user details.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Include the response status code and body if applicable.
      placeholder: eg. Received 500 Internal Server Error with response body {}
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: Indicate the severity of the issue.
      options:
        - P0 (Critical): Production API is down, blocking all users
        - P1 (High): Severe issue affecting multiple users
        - P2 (Medium): Bug affects functionality but has a workaround
        - P3 (Low): Minor issue, does not impact core functionality
        - P4 (Trivial): Cosmetic or non-impactful bug
      default: P2 (Medium)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Traces
      description: Provide any relevant server logs, error messages, or stack traces.
      render: shell
      placeholder: |
        2024-11-12T10:15:45Z ERROR [UserService]: NullReferenceException at UserController.CreateUser

  - type: input
    id: environment
    attributes:
      label: API Environment
      description: Specify the environment where the issue was encountered (e.g., AT22, TT02, PROD).
      placeholder: ex. Production

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other information that might help us diagnose the issue (e.g., recent changes, third-party dependencies).
      placeholder: ex. Recent deployment changes, external API dependencies.