using System.Collections.Generic;

namespace Altinn.Platform.Authentication.Model
{
    /// <summary>
    /// Oidc provider config
    /// </summary>
    public class OidcProvider
    {
        /// <summary>
        /// The OIDC issuer in token
        /// </summary>
        public string Issuer { get; set; }

        /// <summary>
        /// The authorization endpoint
        /// </summary>
        public string AuthorizationEndpoint { get; set; }

        /// <summary>
        /// Token endpoint
        /// </summary>
        public string TokenEndpoint { get; set; }

        /// <summary>
        /// Logout endpoint
        /// </summary>
        public string LogoutEndpoint { get; set; }

        /// <summary>
        /// Issuer key
        /// </summary>
        public string IssuerKey { get; set; }

        /// <summary>
        /// Well known endpoint
        /// </summary>
        public string WellKnownConfigEndpoint { get; set; }

        /// <summary>
        /// Scope to request
        /// </summary>
        public string Scope { get; set; } = "openid";

        /// <summary>
        /// The client Id
        /// </summary>
        public string ClientId { get; set; }

        /// <summary>
        /// The username prefix when usersname is autogenerated
        /// </summary>
        public string UserNamePrefix { get; set; }

        /// <summary>
        /// The client secret
        /// </summary>
        public string ClientSecret { get; set; }

        /// <summary>
        /// The response type
        /// </summary>
        public string ResponseType { get; set; } = "code";

        /// <summary>
        /// A list of non standard claims that should be copied to 
        /// </summary>
        public string ClaimsToCopyTo { get; set; }

        /// <summary>
        /// A list of claims that need to be forwarded to Altinn token
        /// </summary>
        public string[] ProviderClaims { get; set; }

        /// <summary>
        /// The claim to use for external identity if
        /// </summary>
        public string ExternalIdentityClaim { get; set; }

        /// <summary>
        /// Defines if Altinn Authentication should include the iss in the redirect_uri
        /// </summary>
        public bool IncludeIssInRedirectUri { get; set; }

        /// <summary>
        /// Defines the default authentication method
        /// </summary>
        public string DefaultAuthenticationMethod { get; set; } = "SelfIdentified";

        /// <summary>
        /// When true, this provider may only authenticate synthetic (Tenor) test
        /// persons: a token that does not carry a well-formed synthetic
        /// fødselsnummer (month 81–92, valid mod11) — including a token with no
        /// <c>pid</c> claim — is rejected fail-closed. Set this on test-only
        /// providers (e.g. mockporten) so neither an ordinary national identity
        /// number nor a non-pid identity can be authenticated through them.
        /// Default false. See issue #1409 / #1983.
        /// </summary>
        public bool RequireSyntheticPid { get; set; } = false;

        /// <summary>
        /// Which claim in this provider's id_token carries which piece of meaning. Optional —
        /// when omitted, ID-porten's claim names are assumed (<c>pid</c>, <c>acr</c>, <c>amr</c>).
        /// Set this for providers outside that convention, e.g. HelseID.
        /// </summary>
        public OidcClaimMappings? ClaimMappings { get; set; }

        /// <summary>
        /// The authentication levels this provider offers. Optional — when omitted, the provider
        /// is assumed to use ID-porten's acr vocabulary and the built-in level table applies.
        /// <para>
        /// Declaring levels here is what makes a provider reachable: the union of every
        /// configured <see cref="OidcAuthLevel.Acr"/> forms the allow-list for the
        /// <c>acr_values</c> request parameter, and decides which provider a requested acr
        /// routes to.
        /// </para>
        /// </summary>
        public List<OidcAuthLevel>? AuthLevels { get; set; }

        /// <summary>
        /// Maps the values of this provider's authentication-method claim onto Altinn's
        /// <c>AuthenticationMethod</c> enum, e.g. HelseID's <c>idp</c> value
        /// <c>bankid-oidc</c> to <c>BankID</c>. Optional — when omitted, ID-porten's amr values
        /// are assumed. Matched case-insensitively. Unmatched values fall back to
        /// <see cref="DefaultAuthenticationMethod"/>.
        /// </summary>
        public Dictionary<string, string>? AuthMethodMappings { get; set; }

        /// <summary>
        /// The <c>acr_values</c> to send to this provider's authorize endpoint when the client
        /// requested no level. Optional. Replaces the hardcoded ID-porten default, which is not
        /// meaningful for other providers.
        /// </summary>
        public string? DefaultUpstreamAcrValues { get; set; }
    }
}
