-- grant on tables
ALTER DEFAULT PRIVILEGES FOR USER "${YUNIQL-USER}" IN SCHEMA business_application GRANT
SELECT
, INSERT, UPDATE, REFERENCES, DELETE, TRUNCATE, TRIGGER ON TABLES TO "${APP-USER}";

-- grant on sequences
ALTER DEFAULT PRIVILEGES FOR USER "${YUNIQL-USER}" IN SCHEMA business_application GRANT ALL ON SEQUENCES TO "${APP-USER}";

